move:
  ros__parameters:
    plugins:
      - plansys2_move_bt_node
    waypoints: ["corridor", "grandma_pos", "towel_bathroom", "cutlery_kitchen", "milk_kitchen", "tools_garage", "clothes_bedroom", "plants_yard", "magazines_livingroom", "pills_livingroom", "bed_guestroom", "towel_bedroom", "tools_kitchen"]
    waypoint_coords:
      corridor: [1.0, 0.0, 0.0]
      grandma_pos: [3.6, 4.7, 0.0]
      towel_bathroom: [5.4, -6.9, 0.0]
      cutlery_kitchen: [-4.6, -1.2, 0.0]
      milk_kitchen: [-4.2, 1.8, 0.0]
      tools_garage: [-3.7, 11.0, 0.0]
      clothes_bedroom: [5.3, 5.0, 0.0]
      plants_yard: [-4.3, 7.7, 0.0]
      magazines_livingroom: [-4.0, -7.8, 0.0]
      pills_livingroom: [4.7, -4.2, 0.0]
      bed_guestroom: [5.6, 1.6, 0.0]
      towel_bedroom: [5.1, 6.1, 0.0]
      tools_kitchen: [-2.5, -1.3, 0.0]


drop_item:
  ros__parameters:
    plugins:
      - plansys2_drop_item_bt_node

grandma_chores:
  ros__parameters:
    plugins:
      - plansys2_grandma_chores_bt_node

item_for_grandma:
  ros__parameters:
    plugins:
      - plansys2_item_for_grandma_bt_node

move_through_door:
  ros__parameters:
    plugins:
      - plansys2_move_through_door_bt_node
    waypoints: ["p1_living", "p2_living", "p2_bathroom", "p3_corridor", "p3_living", "p4_kitchen", "p4_corridor", "p5_guest", "p5_corridor", "p6_yard", "p6_corridor", "p7_grandma_bed", "p7_corridor", "p8_garage", "p8_corridor"]
    waypoint_coords:
      p1_living: [-3.6, -9.2, 0.0]
      p2_living: [1.4, -7.8, 0.0]
      p2_bathroom: [3.0, -7.8, 0.0]
      p3_corridor: [0.5, -3.7, 0.0]
      p3_living: [0.4, -2.0, 0.0]
      p4_kitchen: [-1.9, 0.0, 0.0]
      p4_corridor: [-0.3, 0.1, 0.0]
      p5_guest: [2.8, 0.2, 0.0]
      p5_corridor: [1.0, 0.3, 0.0]
      p6_yard: [-1.8, 6.1, 0.0]
      p6_corridor: [-0.2, 6.0, 0.0]
      p7_grandma_bed: [2.8, 6.0, 0.0]
      p7_corridor: [1.1, 6.2, 0.0]
      p8_garage: [0.4, -9.8, 0.0]
      p8_corridor: [0.5, 8.1, 0.0]



open_door:
  ros__parameters:
    plugins:
      - plansys2_open_door_bt_node

organize_item:
  ros__parameters:
    plugins:
      - plansys2_organize_item_bt_node

pick_item:
  ros__parameters:
    plugins:
      - plansys2_pick_item_bt_node

request_open_door:
  ros__parameters:
    plugins:
      - plansys2_request_open_door_bt_node
